# Use root/example as user/password credentials
version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    container_name: mymongo
    network_mode: bridge
    ports:
      - "27015:27015"
      - "27017:27017"
    expose:
      # Opens port 3306 on the container
      - "27015"
      - "27017"

  mongo-express:
    image: mongo-express
    restart: always
    container_name: mymongoexpress
    network_mode: bridge
    ports:
      - 8081:8081
    expose:
      - "8081"
    links:
      - mongo:mongo